const endpoint='https://script.google.com/macros/s/AKfycbyyJYKK9nPSZZrJMwyX2hk8aPtynyIz8vd4r8WFvXa3ToplpCv1Di5W8H2Jheo_4LC_7g/exec'
const questions=[
 ['¿Qué tan familiarizado/a estás con las mermeladas caseras o artesanales?',[['Muy familiarizado/a','Las consumo o conozco varias marcas.'],['Familiarizado/a','Las he probado ocasionalmente.'],['Poco familiarizado/a','Me resultan interesantes, pero no las conozco mucho.'],['Nada familiarizado/a','No suelo consumirlas.']]],
 ['¿Con qué frecuencia consumes mermelada?',[['Diariamente','Es parte habitual de mi desayuno.'],['Varias veces por semana','La consumo con frecuencia.'],['Ocasionalmente','Solo algunas veces al mes.'],['Casi nunca','No forma parte de mi compra.']]],
 ['¿Qué perfil de sabor te atrae más?',[['Frutos rojos','Intenso, ácido y familiar.'],['Cítricos','Brillante y fresco.'],['Fruta tropical','Solar y suave.'],['Sabores de temporada','Me gusta probar novedades.']]],
 ['¿Qué diferenciaría a una marca artesanal?',[['Ingredientes naturales','Una lista clara y reconocible.'],['Sabor casero','Que recuerde a una receta familiar.'],['Recetas originales','Combinaciones distintas.'],['Producción en pequeñas cantidades','Más cuidado en cada frasco.']]],
 ['¿Qué nivel de dulzor prefieres?',[['Dulce clásico','El sabor tradicional.'],['Dulzor moderado','Equilibrio entre fruta y azúcar.'],['Poco dulce','Que destaque la fruta.']]],
 ['¿Qué presentación comprarías primero?',[['Frasco pequeño 150 g','Ideal para probar.'],['Frasco mediano 250 g','Buen equilibrio para el hogar.'],['Frasco grande 400 g','Para consumo frecuente.']]],
 ['¿Qué precio considerarías razonable para 250 g?',[['Menos de S/ 18','Busco la opción más accesible.'],['S/ 18 a S/ 26','Precio justo por calidad artesanal.'],['S/ 27 a S/ 38','Acepto pagar más por diferenciación.'],['Más de S/ 38','Lo compraría como producto premium.']]],
 ['¿Dónde te gustaría encontrarla?',[['Redes sociales / mensajería','Pedido directo y cercano.'],['Ferias y mercados','Quiero conocer al productor.'],['Tiendas locales','Me gusta comprar en mi zona.'],['Supermercados','Prefiero la comodidad.']]],
 ['¿En qué ocasión la consumirías?',[['Desayuno cotidiano','Con pan, tostadas o avena.'],['Regalo','Como detalle artesanal.'],['Reuniones','Para compartir.'],['Recetas y repostería','Como ingrediente.']]],
 ['¿Qué elemento te daría más confianza?',[['Ingredientes y etiqueta clara','Quiero saber qué estoy comprando.'],['Recomendaciones','Confío en opiniones cercanas.'],['Historia de la marca','Me importa quién lo produce.'],['Prueba o degustación','Prefiero probar antes.']]],
 ['¿Cómo debería posicionarse CasaFruta?',[['Artesanal accesible','Calidad cercana y precio razonable.'],['Producto premium','Una experiencia especial.'],['Saludable y natural','El foco está en los ingredientes.'],['Regalo con identidad','Un detalle con personalidad.']]],
 ['¿Qué te motivaría más a probar una mermelada nueva?',[['Fruta de productores locales','Me importa el origen y apoyar lo cercano.'],['Receta baja en azúcar','Busco equilibrio sin renunciar al sabor.'],['Envase reutilizable','Valoro una compra con menor impacto.'],['Edición limitada','Me atraen las novedades y la exclusividad.']]],
 ['¿Qué experiencia te gustaría encontrar junto al frasco?',[['Pack de degustación','Quiero probar varios sabores antes de elegir.'],['Suscripción mensual','Me gustaría recibir novedades periódicamente.'],['Etiqueta personalizada','La compraría como regalo con un toque propio.'],['Recetas y maridajes','Me interesa aprender nuevas formas de usarla.']]],
 ['¿Qué te haría recomendar CasaFruta a otra persona?',[['Sabor memorable','La recomendaría si realmente sorprende.'],['Precio coherente','La relación calidad-precio sería decisiva.'],['Historia auténtica','Me gusta compartir marcas con propósito.'],['Disponibilidad sencilla','Debe ser fácil volver a comprarla.']]],
 ['Si estuviera disponible hoy, ¿qué tan probable sería que la compraras?',[['Muy probable','La compraría en mi próxima compra.'],['Probable','Me interesaría probarla.'],['Poco probable','Necesitaría más información.'],['Nada probable','No es una categoría que me interese.']]]
]
const form=document.querySelector('#survey-form'), progress=document.querySelector('#progress'), progressLine=document.querySelector('.progress-line'), result=document.querySelector('#survey-result'), startPanel=document.querySelector('#start-panel'), startButton=document.querySelector('#start-survey'), alreadyCompleted=document.querySelector('#already-completed');const storageKey='casafruta-survey-submitted-v2';let current=0;const answers={}
function render(){form.innerHTML=questions.map(([question,options],i)=>`<section class="question ${i===0?'active':''}" data-index="${i}"><div class="question-num">${String(i+1).padStart(2,'0')} / ${questions.length}</div><h2>${question}</h2><div class="options">${options.map(([label,help])=>`<label class="option"><input type="radio" name="q${i+1}" value="${label}"><b>${label}</b><small>${help}</small></label>`).join('')}</div>${i<questions.length-1?'<button type="button" class="button button-dark next">Siguiente <span>→</span></button>':'<button type="submit" class="button button-dark next">Enviar respuestas <span>↗</span></button>'}</section>`).join('')}
function show(i){current=i;document.querySelectorAll('.question').forEach((el,n)=>el.classList.toggle('active',n===i));progress.style.width=`${(Object.keys(answers).length/questions.length)*100}%`;window.scrollTo({top:0,behavior:'smooth'})}
function beginSurvey(){startPanel.hidden=true;form.hidden=false;progressLine.hidden=false;show(0)}
if(localStorage.getItem(storageKey)==='true'){startPanel.hidden=true;alreadyCompleted.hidden=false}else{startButton.addEventListener('click',beginSurvey)}
render();form.addEventListener('change',e=>{if(e.target.matches('input')){answers[e.target.name]=e.target.value}});form.addEventListener('click',e=>{const button=e.target.closest('.next');if(!button)return;const section=button.closest('.question'),i=Number(section.dataset.index);if(!answers[`q${i+1}`]){section.animate([{transform:'translateX(-5px)'},{transform:'translateX(5px)'},{transform:'none'}],{duration:260});return}if(i<questions.length-1)show(i+1)});form.addEventListener('submit',async e=>{e.preventDefault();if(Object.keys(answers).length<questions.length)return;const payload={timestamp:new Date().toISOString(),...answers};let sent=false;try{await fetch(endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});sent=true}catch{}localStorage.setItem(storageKey,'true');form.hidden=true;result.hidden=false;result.querySelector('#result-copy').textContent=sent?'Tu respuesta fue registrada y ayudará a definir sabores, precio y presentación.':'La respuesta quedó preparada; puedes volver a intentarlo si no aparece en el tablero.';progress.style.width='100%';result.scrollIntoView({behavior:'smooth'})})
